services:
  - type: web
    name: campus-event-formation
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus-event-db
          property: connectionString
      - key: JWT_SECRET
        value: campus_event_secret_key
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false

databases:
  - name: campus-event-db
    plan: free
    region: oregon
